from flask import Flask,request
import json
import logging
from datetime import datetime
from dotenv import load_dotenv
import os

load_dotenv(override=True)  # Load environment variables from .env file
verifyToken =  os.getenv("VERIFY_TOKEN")

logging.basicConfig(
    level=logging.INFO, 
    format='%(asctime)s - %(levelname)s - %(message)s', 
    datefmt='%Y-%m-%d %H:%M:%S', 
    handlers=[
        logging.FileHandler("webhook.log"), 
        logging.StreamHandler()
    ]
)

app = Flask(__name__)


@app.route('/webhook', methods=['GET'])
def verify_webhook():
    """Handle WhatsApp webhook verification request from Meta.

    Meta sends a GET request to this endpoint when you register or update
    your webhook URL in the Meta Dashboard. This is a one-time handshake
    that proves you own the server at this URL.

    Meta's request includes three query parameters:
        - hub.mode: Always "subscribe" for new webhook registrations.
        - hub.verify_token: The secret token you configured in the Meta
          Dashboard. Must match the VERIFY_TOKEN environment variable.
        - hub.challenge: A random string generated by Meta. Must be
          returned as-is in the response body to complete verification.

    The verification follows the PubSubHubbub/WebSub protocol that Meta
    adopted across all Graph API products (WhatsApp, Instagram, Facebook).

    Returns:
        On success (200): The hub.challenge string as plain text.
            Meta receives this, confirms it matches, and activates
            the webhook. Messages will start flowing to the POST endpoint.
        On failure (403): "Verification failed" when the verify token
            doesn't match or hub.mode is not "subscribe".
        On error (500): "Internal Server Error" if an unexpected
            exception occurs during processing.

    Example Meta request:
        GET /webhook?hub.mode=subscribe
                    &hub.verify_token=your_secret
                    &hub.challenge=1234567890

    Example success response:
        Status: 200
        Body: 1234567890
    """

    logging.info("Received webhook verification request")
    try:
        logging.info("Request args: %s", json.dumps(request.args.to_dict(), indent=2))
        mode = request.args.get('hub.mode')
        token = request.args.get('hub.verify_token')
        challenge = request.args.get('hub.challenge')
        if mode == 'subscribe' and token == verifyToken:
            logging.info("Webhook verified successfully")
            return challenge, 200
        else:
            logging.warning("Webhook verification failed: Invalid token or mode")
            return 'Verification failed', 403
    except Exception as e:
        logging.error("Error occurred while verifying webhook: %s", str(e))
        return 'Internal Server Error', 500


@app.route('/webhook', methods=['POST'])
def handle_webhook():
    """Receive and process incoming WhatsApp webhook events from Meta.

    Once the webhook is verified via the GET endpoint, Meta sends a POST
    request to this endpoint whenever an event occurs on your WhatsApp
    Business account. Events include incoming messages, delivery status
    updates, and read receipts.

    Meta always sends the payload as JSON with this top-level structure:
        {
            "object": "whatsapp_business_account",
            "entry": [{
                "id": "<WABA_ID>",
                "changes": [{
                    "value": {
                        "messaging_product": "whatsapp",
                        "metadata": { ... },
                        "contacts": [ ... ],
                        "messages": [ ... ],
                        "statuses": [ ... ]
                    },
                    "field": "messages"
                }]
            }]
        }

    Not every POST contains messages. Some contain only status updates
    (sent, delivered, read). The handler must check for the presence of
    each field before processing.

    Supported message types in value.messages:
        - text: Plain text messages (body in message.text.body)
        - image: Photos (media ID in message.image.id)
        - video: Videos (media ID in message.video.id)
        - audio: Voice notes and audio files (message.audio.id)
        - document: PDFs, docs, etc. (message.document.id)
        - location: Shared locations (lat/lng in message.location)
        - contacts: Shared contact cards (message.contacts)
        - reaction: Emoji reactions to messages (message.reaction.emoji)
        - interactive: Button/list replies (message.interactive)
        - sticker: Sticker messages (message.sticker.id)

    Status updates in value.statuses:
        - sent: Message was sent to Meta's servers
        - delivered: Message reached the recipient's device
        - read: Recipient opened and read the message
        - failed: Message delivery failed (includes error details)

    Important:
        This endpoint MUST always return HTTP 200, even if processing
        fails. If Meta receives a non-200 response, it will retry the
        delivery with exponential backoff and eventually disable the
        webhook after repeated failures.

    Returns:
        Always returns 200 with "Event received" to acknowledge
        the webhook delivery, regardless of processing outcome.

    Example incoming text message payload:
        {
            "object": "whatsapp_business_account",
            "entry": [{
                "changes": [{
                    "value": {
                        "contacts": [{
                            "profile": {"name": "John"},
                            "wa_id": "94771234567"
                        }],
                        "messages": [{
                            "from": "94771234567",
                            "id": "wamid.HBgN...",
                            "timestamp": "1693500000",
                            "type": "text",
                            "text": {"body": "Hello!"}
                        }]
                    },
                    "field": "messages"
                }]
            }]
        }
    """

    logging.info("Received webhook event")
    try:
        data = request.get_json()
        logging.info("Webhook payload: %s", json.dumps(data, indent=2))
        # Process the webhook event here
        return 'Event received', 200
    except Exception as e:
        logging.error("Error occurred while handling webhook event: %s", str(e))
        return 'Internal Server Error', 500


if __name__ == '__main__':
    app.run(host='localhost', port=3000, debug=True)