"""create initial whatsapp mcp schema for storing user data and messages

Revision ID: c0061bfe2efb
Revises: 
Create Date: 2026-10-07 11:48:35.553158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0061bfe2efb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_numbers',
    sa.Column('wapn_id', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('wa_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('label', sa.Enum('SUPPORT', 'SALES', 'CHATBOT', name='phonenumberlables'), nullable=False),
    sa.PrimaryKeyConstraint('wapn_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_wa_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_wa_id', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wapn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['wapn_id'], ['phone_numbers.wapn_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_customer_wa_id'), 'conversations', ['customer_wa_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_wa_user_id'), 'conversations', ['customer_wa_user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wapn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['wapn_id'], ['phone_numbers.wapn_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='messagedirection'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', name='messagestatus'), nullable=False),
    sa.Column('viewed_by', sa.Uuid(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messaged_by', sa.Uuid(), nullable=True),
    sa.Column('reply_msg_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['messaged_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reply_msg_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['viewed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_messages_messaged_by', 'messages', ['messaged_by'], unique=False)
    op.create_index('idx_messages_status', 'messages', ['status'], unique=False)
    op.create_index('idx_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.create_index('idx_messages_viewed_by', 'messages', ['viewed_by'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_table('message_status',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_status')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index('idx_messages_viewed_by', table_name='messages')
    op.drop_index('idx_messages_timestamp', table_name='messages')
    op.drop_index('idx_messages_status', table_name='messages')
    op.drop_index('idx_messages_messaged_by', table_name='messages')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_conversations_customer_wa_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_wa_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('phone_numbers')
    # ### end Alembic commands ###
