"""expand phone number id length

Revision ID: c6da89da1931
Revises: c0061bfe2efb
Create Date: 2026-10-08 01:22:44.426367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6da89da1931'
down_revision: Union[str, Sequence[str], None] = 'c0061bfe2efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_numbers', 'wapn_id',
               existing_type=sa.VARCHAR(length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    op.alter_column('phone_numbers', 'wa_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sqlmodel.sql.sqltypes.AutoString(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_numbers', 'wa_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=32),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('phone_numbers', 'wapn_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
