"""revise messages, conversations and enum columns

Revision ID: cbc3a6dfeb5f
Revises: c6da89da1931
Create Date: 2026-10-10 09:58:41.024726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbc3a6dfeb5f'
down_revision: Union[str, Sequence[str], None] = 'c6da89da1931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('last_handled_by', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    op.create_index('idx_conv_inbox', 'conversations', ['wapn_id', 'last_message_at'], unique=False)
    op.create_unique_constraint('uq_conv_number_customer', 'conversations', ['wapn_id', 'customer_wa_id'])
    op.create_foreign_key(None, 'conversations', 'users', ['last_handled_by'], ['user_id'])
    op.add_column('messages', sa.Column('wa_message_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('messages', 'direction',
               existing_type=postgresql.ENUM('IN', 'OUT', name='messagedirection'),
               type_=sa.Enum('IN', 'OUT', name='messagedirection', native_enum=False, length=10),
               existing_nullable=False)
    op.alter_column('messages', 'status',
               existing_type=postgresql.ENUM('SENT', 'DELIVERED', 'READ', name='messagestatus'),
               type_=sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'RECEIVED', name='messagestatus', native_enum=False, length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_messages_conversation'), table_name='messages')
    op.drop_index(op.f('idx_messages_status'), table_name='messages')
    op.drop_index(op.f('idx_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('idx_messages_viewed_by'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.create_index('idx_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'messages', ['wa_message_id'])
    op.alter_column('phone_numbers', 'label',
               existing_type=postgresql.ENUM('SUPPORT', 'SALES', 'CHATBOT', name='phonenumberlables'),
               type_=sa.Enum('SUPPORT', 'SALES', 'CHATBOT', name='phonenumberlabels', native_enum=False, length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_numbers', 'label',
               existing_type=sa.Enum('SUPPORT', 'SALES', 'CHATBOT', name='phonenumberlabels', native_enum=False, length=20),
               type_=postgresql.ENUM('SUPPORT', 'SALES', 'CHATBOT', name='phonenumberlables'),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_index('idx_messages_conv_created', table_name='messages')
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('idx_messages_viewed_by'), 'messages', ['viewed_by'], unique=False)
    op.create_index(op.f('idx_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('idx_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('idx_messages_conversation'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'status',
               existing_type=sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'RECEIVED', name='messagestatus', native_enum=False, length=20),
               type_=postgresql.ENUM('SENT', 'DELIVERED', 'READ', name='messagestatus'),
               existing_nullable=False)
    op.alter_column('messages', 'direction',
               existing_type=sa.Enum('IN', 'OUT', name='messagedirection', native_enum=False, length=10),
               type_=postgresql.ENUM('IN', 'OUT', name='messagedirection'),
               existing_nullable=False)
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'wa_message_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint('uq_conv_number_customer', 'conversations', type_='unique')
    op.drop_index('idx_conv_inbox', table_name='conversations')
    op.drop_column('conversations', 'is_resolved')
    op.drop_column('conversations', 'last_handled_by')
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'last_inbound_at')
    # ### end Alembic commands ###
